"""empty message

Revision ID: a0ce2347fc88
Revises: 5b7a33c006e9
Create Date: 2025-02-28 09:21:13.166677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0ce2347fc88'
down_revision = '5b7a33c006e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))
        batch_op.drop_constraint('user_user_name_key', type_='unique')
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('user_user_name_key', ['user_name'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###
